"""empty message

Revision ID: 5f9f55d50f66
Revises: 5729ba777cf8
Create Date: 2023-04-02 17:09:27.634517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9f55d50f66'
down_revision = '5729ba777cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('locations_type_key', type_='unique')
        batch_op.create_unique_constraint(None, ['tipo'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('locations_type_key', ['type'])
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
